### ISSUE TITLE
panic: WriteHeader called after Handler finished

### ISSUE THREAD

**Issue by kwzcoder** [micro-in-cn/questions#54]
micro  api  小概率出现:

2020-03-11 17:48:33.528991 I | http: proxy error: context canceled
panic: WriteHeader called after Handler finished

goroutine 198 [running]:
net/http.(*http2responseWriter).WriteHeader(0xc000010048, 0x1f6)
        /usr/local/go/src/net/http/h2_bundle.go:6187 +0x63
github.com/gorilla/handlers.(*responseLogger).WriteHeader(0xc0001b8180, 0x1f6)
        /Users/qushi/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/handlers.go:65 +0x3d
qtimes.cc/galileo/microservices/lib/http.(*StatusCodeTracker).WriteHeader(0xc0001b8280, 0x1f6)
        /Users/qushi/go/src/qtimes.cc/galileo/microservices/lib/http/status-code-tracker.go:19 +0x41
qtimes.cc/galileo/microservices/lib/http.(*StatusCodeTracker).WriteHeader(0xc0001b8340, 0x1f6)
        /Users/qushi/go/src/qtimes.cc/galileo/microservices/lib/http/status-code-tracker.go:19 +0x41
net/http/httputil.(*ReverseProxy).defaultErrorHandler(0xc00025f720, 0x5505f20, 0xc00003d600, 0xc0001e6100, 0x54d16e0, 0xc0000741e0)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:153 +0xa2
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc00025f720, 0x5505f20, 0xc00003d600, 0xc0001dc900)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:251 +0xe78
github.com/micro/go-micro/api/handler/http.(*httpHandler).ServeHTTP(0xc00003c100, 0x5505f20, 0xc00003d600, 0xc0001dc900)
        /Users/qushi/go/pkg/mod/github.com/micro/go-micro@v1.18.0/api/handler/http/http.go:45 +0xcf
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002f0000, 0x5505f20, 0xc00003d600, 0xc0001dc500)
        /Users/qushi/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
qtimes.cc/galileo/microservices/lib/wrapper/metrics/prometheus.MetricsWrapper.func1(0x5505f20, 0xc00003d600, 0xc0001dc500)
        /Users/qushi/go/src/qtimes.cc/galileo/microservices/lib/wrapper/metrics/prometheus/prometheus.go:19 +0x77
net/http.HandlerFunc.ServeHTTP(0xc00018a000, 0x5505f20, 0xc00003d600, 0xc0001dc500)
        /usr/local/go/src/net/http/server.go:2007 +0x44
qtimes.cc/galileo/microservices/lib/wrapper/breaker/hystrix.BreakerWrapper.func1.1(0x4051228, 0x5d8762b53bd74)
        /Users/qushi/go/src/qtimes.cc/galileo/microservices/lib/wrapper/breaker/hystrix/hystrix.go:21 +0xc3
github.com/afex/hystrix-go/hystrix.Do.func1(0x550b320, 0xc0000440a0, 0x40c22f6, 0x5e68b3f0)
        /Users/qushi/go/pkg/mod/github.com/afex/hystrix-go@v0.0.0-20180502004556-fa1af6a1f4f5/hystrix/hystrix.go:204 +0x26
github.com/afex/hystrix-go/hystrix.DoC.func1(0x550b320, 0xc0000440a0, 0x5fc0720, 0x0)
        /Users/qushi/go/pkg/mod/github.com/afex/hystrix-go@v0.0.0-20180502004556-fa1af6a1f4f5/hystrix/hystrix.go:221 +0x46
github.com/afex/hystrix-go/hystrix.GoC.func3(0xc00015a3f0, 0xc0004e612c, 0xc00003d5c0, 0xc0004e6130, 0xc0001b8300, 0x550b320, 0xc0000440a0, 0xc0004e4540, 0xc00003d500, 0xc0001b82a0)
        /Users/qushi/go/pkg/mod/github.com/afex/hystrix-go@v0.0.0-20180502004556-fa1af6a1f4f5/hystrix/hystrix.go:160 +0x180
created by github.com/afex/hystrix-go/hystrix.GoC
        /Users/qushi/go/pkg/mod/github.com/afex/hystrix-go@v0.0.0-20180502004556-fa1af6a1f4f5/hystrix/hystrix.go:116 +0x325
make: *** [run] Error 2

**Comment by printfcoder** [comment]
#issue-590030698

**Comment by printfcoder** [comment]
#52
